### ISSUE TITLE
Walkthrough about OIDC (OpenID Connect)

### ISSUE THREAD

**Issue by mtlaso** [Alex-Yakubovsky/walkthroughs#2]
First of all,

Thank you very much for your walkthroughs (especially the one about OAuth). They help me a lot. I'm very grateful for them. The reason I am creating an issue is to have updates about the OIDC walkthrough, inferred at [the end of the OAuth walkthrough](https://annotate.dev/p/hello-world/learn-oauth-2-0-by-building-your-own-oauth-client-U2HaZNtvQojn4F),

> ...In the next walkthrough, you'll explore OIDC—what problems it addresses and the minimal code adjustments needed to support it. Stay tuned!

Additionally, regarding the OAuth walkthrough, OAuth 2.1 might replace OAuth 2.0 in the future, so maybe it's worth an update and/or specifying this on the current walkthrough.

Thanks again!

**Comment by Alex-Yakubovsky** [comment]
Glad you found it helpful! I'm just finishing up some more features for annotate.dev, then I'll get to writing about OIDC.

Thanks for bringing up the OAuth 2.1 RFC, I wasn't aware! Looks like part of it is having PKCE as part of the spec, which is neat. I'll make sure to either update the guide or create a new one once it's been standardized.
